language: node_js

sudo: required
node_js:
- 'stable'

install:
- npm install -g firebase-tools

script:
- yarn build

after_success:
- yarn sonar
- npm install -g firebase-tools
- firebase deploy --token "$FIREBASE_TOKEN" --project "grafos-evolucao-maturidade"

addons:
  sonarcloud:
    organization: matheusaraujo
    token:
      secure: $SONAR_TOKEN