language: node_js
node_js:
  - "7"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - yarn build
  - firebase deploy --project grafos-evolucao-maturidade --token $FIREBASE_TOKEN