language: node_js
dist: trusty
sudo: required
node_js:
- 'stable'
#script:
#- sonar-scanner
before_install:
- curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- npm install -g firebase-tools
after_success:
- yarn build
- firebase deploy --project grafos-evolucao-maturidade --token $FIREBASE_TOKEN
#addons:
#  sonarcloud:
#    organization: matheusaraujo
#    token:
#      secure: $SONAR_TOKEN
cache:
  yarn: true