language: node_js

sudo: required
node_js:
- 'stable'

install:
- npm install -g firebase-tools

script:
- yarn install
- yarn build

after_success:
- yarn sonar

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "grafos-evolucao-maturidade"
  message: $TRAVIS_COMMIT_MESSAGE
  skip_cleanup: true

addons:
  sonarcloud:
    organization: matheusaraujo
    token:
      secure: $SONAR_TOKEN