language: node_js
dist: trusty
node_js:
- '10'
script:
- sonar-scanner
install:
- npm install -g firebase-tools
- curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
after_success:
- yarn build
- firebase deploy --project grafos-evolucao-maturidade --token $FIREBASE_TOKEN
addons:
  sonarcloud:
    organization: matheusaraujo
    token:
      secure: $SONAR_TOKEN