language: node_js
#dist: trusty
sudo: required
node_js:
- 'stable'
#script:
#- sonar-scanner
#before_install:
#- curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
#- export PATH=$HOME/.yarn/bin:$PATH

install:
- npm install -g firebase-tools

script:
- yarn build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "grafos-evolucao-maturidade"
  message: $TRAVIS_COMMIT_MESSAGE
  skip_cleanup: true

  # - firebase deploy --project grafos-evolucao-maturidade --token $FIREBASE_TOKEN
#addons:
#  sonarcloud:
#    organization: matheusaraujo
#    token:
#      secure: $SONAR_TOKEN

# cache:
#  yarn: true