language: node_js
dist: trusty
node_js:
- '10'
branches:
  only:
  - master

install:
- npm install -g firebase-tools
after_success:
- yarn build
- sonar-scanner
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "grafos-evolucao-maturidade"

addons:
  sonarcloud:
    organization: matheusaraujo
    token:
      secure: $SONAR_TOKEN