language: node_js
dist: trusty
node_js:
- '10'
branches:
  only:
  - master

install:
- npm install -g firebase-tools
script:
- yarn build
after_success:
- sonar-scanner
deploy:
- firebase deploy --project grafos-evolucao-maturidade --token $FIREBASE_TOKEN

addons:
  sonarcloud:
    organization: matheusaraujo
    token:
      secure: $SONAR_TOKEN