theme: jekyll-theme-minimal

title: grafos-evolucao-maturidade
description: Lorem ipsum dolor sit amet.
logo: https://github.com/matheusaraujo/grafos-evolucao-maturidade/raw/master/docs/logo.jpg
show_downloads: true
